### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by cagrihakkoymaz** [megvii-research/MCTrack#11]
Firstly, congratulations on your success, and thank you for sharing this valuable work with the community!

I wanted to ask if there is any specific method or tool you prefer for visualizing detections and tracks for debug and further improvement?

**Comment by wangxiyang2022** [comment]
Thank you for your interest in our work! 

We completely agree that visualization is very important for MOT. In fact, we have used some visualization tools to examine our tracking results in the early stages. Since these tools require the installation of some of our internal library files, we have not made them open source in MCTrack. We recommend some very useful visualization tools, such as [3D-Detection-Tracking-Viewer](https://github.com/hailanyi/3D-Detection-Tracking-Viewer), which can be used to visualize 3D detection and tracking boxes.
